---
- name: Prepare pgAdmin environment
  hosts: control_plane
  vars:
    project_dir: /home/data
    ansible_user: homelab_admin

  tasks:
    - name: Create pgAdmin data directory
      file:
        path: "{{ project_dir }}/pgadmin/data"
        state: directory
        owner: "{{ ansible_user }}"
        mode: '0766'
