---
- name: Prepare PostgreSQL environment
  hosts: control_plane
  tasks:
  - name: Create PostgreSQL data directory
    file:
      path: "{{ project_dir }}/postgres/data"
      state: directory
      owner: {{ ansible_user }}
      group: {{ ansible_user }}